### ISSUE TITLE
Obtaining data from predefined chunks and using it in world generation

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/TopDownGame#5]
All chunks in the world are generated by custom plane meshes created from script. The chunk on the right was generated from FastNoiseLite data and the chunk on the left was generated from a predefined PackedScene using Godot's TileMaps.

![Untitled](https://github.com/valkyrienyanko/TopDownGame/assets/6277739/313d75fa-f6c8-4640-a2f2-85d09426ec92)

The idea is all the chunks generated from noise data are created first and then there is a small chance for a predefined chunk to randomly appear in the world and replace the randomly generated tiles with predefined tiles.

In the picture above you can see that the predefined chunk is the same size as the noise chunk. But the predefined chunk should be able to cover any number of chunks. This way artists created the predefined chunks are not limited to one chunk.

So far the predefined and noise chunk are both being created in separate meshes. But this will need to change. There should only be one mesh. The noise data should be generated first and then the predefined data should replace the noise data. Then and only then should the mesh be generated.

On the [predefined branch](https://github.com/valkyrienyanko/TopDownGame/tree/predefined) you will find the above picture setup in this commit 61e6d5f8a50c782258e69975c6bfcd01e9ca83e4. In the commit after that b09a7c28474154a6ae3b63e802ff298bcad3d526 you will find that I have tried to experiment with saving / loading multiple predefined chunk data.

![Untitled](https://github.com/valkyrienyanko/TopDownGame/assets/6277739/5f37d577-635b-4c01-971a-a96c75f31fc2)

This picture shows the defined chunk scene now holds 4 chunks. Notice how the center chunk is to the bottom right of the editor origin. I thought it would be easier to keep track of where each chunk was by defining the center chunk here.

There is a script attached to this scene.

```cs
public partial class DefinedChunk : Node2D
{
    public List<TileLayerPredefined> TileLayers { get; } = new();

    public void Init()
    {
        foreach (TileMap tileMap in GetChildren())
        {
            var layer0 = 0;
            var sourceId = 0;
            var tileAtlas = tileMap.TileSet.GetSource(sourceId) as TileSetAtlasSource;
            var tileLayer = new TileLayerPredefined
            {
                Image = tileAtlas.Texture,
                ZIndex = tileMap.ZIndex
            };

            foreach (var pos in tileMap.GetUsedCells(layer0))
            {
                var uvs = tileMap.GetCellAtlasCoords(layer0, pos);

                var chunkX = (int)Mathf.Floor(pos.X / World.ChunkSize);
                var chunkY = (int)Mathf.Floor(pos.Y / World.ChunkSize);

                //GD.Print($"({chunkX}, {chunkY})");

                tileLayer.Data[new Vector2I(chunkX, chunkY)][pos] = uvs;
            }

            TileLayers.Add(tileLayer);
        }
    }
}
```

I know for sure that the `pos` and `uvs` are 100% correct. But I am not sure about `chunkX`, `chunkY`. I'm not sure how to test if this code works or not. I tried to printing the data to console and the numbers felt off.

The data is stored in a list containing these classes.

```cs
public class TileLayerPredefined
{
    public Dictionary<Vector2I, Dictionary<Vector2I, Vector2I>> Data { get; } = new();
    public Texture2D Image { get; set; }
    public int ZIndex { get; set; }
}
```

I'm not a fan of the `Dictionary<Vector2I, Dictionary<Vector2I, Vector2I>>`. Because for one how do you define the inner dictionary whenever you add a new element to the outer dictionary, you would need a fancy custom function to handle that. And it looks really confusing at first glance unless you see how it's being used in DefinedChunk.cs. I thought of doing something like Dictionary<Chunk, ...> and putting Vector2I Position property in Chunk but that seems to be even more confusing. I'm not sure.

In World.cs this is how the data is extracted from the PackedScene.
```cs
var prefab = GD.Load<PackedScene>("res://Scenes/Prefabs/test.tscn");
var definedChunk = prefab.Instantiate<DefinedChunk>();
definedChunk.Init();

var tileLayers = definedChunk.TileLayers;
// do something with tileLayers...

definedChunk.QueueFree();
```

Currently I'm not doing anything with this data in commit b09a7c28474154a6ae3b63e802ff298bcad3d526 but if you want to see how this data is used then look at the previous commit 61e6d5f8a50c782258e69975c6bfcd01e9ca83e4

**Comment by valkyrienyanko** [comment]
Someone was seeing black lines rendered on their screen when they moved around the meshes but they did not see them when they moved around Godot.TileMaps. So because of this, and not to mention Godot is always continuing to improve their systems I say we should move back to Godots tilemaps. Doing so would also make the codebase much less complex.

**Comment by JamesDepret** [comment]
> Someone was seeing black lines rendered on their screen when they moved around the meshes but they did not see them when they moved around Godot.TileMaps. So because of this, and not to mention Godot is always continuing to improve their systems I say we should move back to Godots tilemaps. Doing so would also make the codebase much less complex.

I'll validate it tonight

**Comment by valkyrienyanko** [comment]
Well either way, most likely going to switch over to TileMaps. Even in the Godot release that just came out they worked on improving the TileMaps.
